### PR TITLE
Support Java 14

### PR DESCRIPTION
**Pull request by NingZhang-e**
To support Java 14

### CODE REVIEW

**Comment by thanhminhmr** [comment]
You should also change the first line of the readme file.

> This is a fork of the aspectj-maven-plugin that has Java 11 support.

**Comment by NingZhang-e** [comment]
> You should also change the first line of the readme file.
> 
> This is a fork of the aspectj-maven-plugin that has Java 11 support.

Updated. Thanks for notification.
Hope @nickwongdev could have one look at the changes and give comments.

**Comment by johanhaleby** [comment]
@nickwongdev Would be great if you could accept this PR and add support for Java 14 as well.

**Comment by johanhaleby** [comment]
I've forked this to https://github.com/johanhaleby/aspectj-maven-plugin and released it to maven central:

```xml
<dependency>
	<groupId>se.haleby.aspectj</groupId>
	<artifactId>aspectj-maven-plugin</artifactId>
	<version>1.12.7</version>
</dependency>
```

**Comment by NingZhang-e** [comment]
No response for long time. Close it. 
Will figure out another way.

**Comment by NingZhang-e** [comment]
@johanhaleby , I decides to adopt your fork and will contribute to your fork in the future.

**Pull request closed without merging**
